Repository sonatype-nexus-community/nexus-repository-helm, pull requests merged in 2020-03, with the labels that each got.

#120 Updating Permanent Instructions for new path in 3.21
  README.md
Labels: review

#121 nexus-cleanup scope should be 'provided' …
  nexus-repository-helm/pom.xml
Labels: cla:signed

#116 Change source of copy command in Dockerfile
  Dockerfile
Labels: cla:signed

#123 NEXUS-23275: Support 3.22.0
  nexus-repository-helm-it/src/test/java/org/sonatype/nexus/plugins/helm/rest/ResourceITSupport.java
  pom.xml
Labels: wip
